version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    target-branch: "feature/dependency-updates"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      javascript:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
